### ISSUE TITLE
Declaration files

### ISSUE THREAD

**Issue by louy** [electricessence/TypeScript.NET#29]
Hi, Does this library come with declaration files? If not, then how are we supposed to use it?

**Comment by electricessence** [comment]
When using modules, defining a .d.ts file becomes problematic because modules don't require namespaces etc.  This library is not intended for use as a monolith like jQuery, or other libraries.  The intention is to only use what you need via a module loader of some kind.   If you can imagine, after a while, this library could be huge, and even though you wanted just one class from it, like TimeSpan, you end up importing everything.

When including this project with yours, you can simply point to the actual source files for type declarations.

If you have a specific use case I can look at, I might be able to come up with a better way to serve the files.
