### ISSUE TITLE
Enumerable Class

### ISSUE THREAD

**Issue by lommez** [electricessence/TypeScript.NET#55]
I saw in d.ts that the Enumerable class doesn´t exist anymore.
In it´s place should I use LinqEnumerable of FiniteEnumerable?

Thanks

**Comment by electricessence** [comment]
@lommez Not exactly...
1) LinqEnumerable is the 'actual class' that does the work.
But Enumerable is the module (static utility) that has methods like from().

**Comment by electricessence** [comment]
2) This allowed me to simplify the module's usage a bit while keeping its integrity.

So now you can:
```ts
var myResult = Enumerable(source).where(predicate).select(selector).toArray();
```

**Comment by electricessence** [comment]
Which before you would have to:
```ts
var myResult = Enumerable.from(source).where(predicate).select(selector).toArray();
```

**Comment by electricessence** [comment]
```InfiniteEnumerable``` was an innovation I did to have a smaller interface for enumerations that don't end and that you shouldn't attempt to get a single result from.  So I did my best to isolate methods that could process an endless enumerable into ```InfiniteEnumerable```, then extend that to ```LinqEnumerable``` (aka FiniteEnumerable) so that ```LinqEnumerable``` has all the expected LINQ methods (and more).

**Comment by lommez** [comment]
Very good
Thanks!
